# Generated by Django 4.1.5 on 2023-01-17 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='company_id',
            new_name='company',
        ),
    ]
