# Generated by Django 4.1.5 on 2023-01-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_company_company_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
