# Generated by Django 4.1.5 on 2023-01-19 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_transactionproductsizedetail_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
