# Generated by Django 4.1.5 on 2023-01-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_transaction_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionproductsizedetail',
            name='number_of_product',
            field=models.IntegerField(null=True),
        ),
    ]
