# Generated by Django 4.1.5 on 2023-01-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_transaction_total_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_type', models.CharField(default='S', max_length=50)),
                ('country', models.CharField(default='Nepal', max_length=50)),
                ('district', models.CharField(max_length=50, null=True)),
                ('province', models.CharField(max_length=50, null=True)),
                ('municipality_type', models.CharField(max_length=50, null=True)),
                ('municipality', models.CharField(max_length=50, null=True)),
                ('ward_no', models.IntegerField(null=True)),
                ('pan_number', models.CharField(max_length=12, null=True, unique=True)),
                ('shop_keeper_name', models.CharField(max_length=50, null=True)),
                ('shop_keeper_phone', models.CharField(max_length=10, null=True)),
                ('manager_name', models.CharField(max_length=50, null=True)),
                ('manager_phone', models.CharField(max_length=10, null=True)),
                ('client_phone', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('product_type_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='company',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='company',
        ),
        migrations.RemoveField(
            model_name='transactionproductdetail',
            name='product',
        ),
        migrations.RemoveField(
            model_name='transactionproductdetail',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='transactionproductsizedetail',
            name='product',
        ),
        migrations.RemoveField(
            model_name='transactionproductsizedetail',
            name='transaction',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='TransactionProductDetail',
        ),
        migrations.DeleteModel(
            name='TransactionProductSizeDetail',
        ),
    ]
