# Generated by Django 4.1.5 on 2023-01-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_client_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ward_no',
            field=models.TextField(max_length=2, null=True),
        ),
    ]
