# Generated by Django 4.1.5 on 2023-01-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_client_ward_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='emial',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
