# Generated by Django 4.1.5 on 2023-01-31 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_client_emial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='emial',
            new_name='email',
        ),
    ]
