# Generated by Django 4.1.5 on 2023-01-31 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
