# Generated by Django 4.1.5 on 2023-01-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_product_product_type_delete_producttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
