# Generated by Django 4.1.5 on 2023-02-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_transaction_transactionproductsizedetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
