# Generated by Django 4.1.5 on 2023-02-01 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_product_available_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_sizes',
        ),
    ]
