# Generated by Django 4.1.5 on 2023-02-06 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_product_available_sizes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionproductsizedetail',
            old_name='number_of_product',
            new_name='number_of_products',
        ),
    ]
