# Generated by Django 4.1.5 on 2023-02-10 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_totalproductcount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totalproductcount',
            old_name='no_of_products',
            new_name='number_of_products',
        ),
        migrations.RenameField(
            model_name='totalsizecount',
            old_name='no_of_products',
            new_name='number_of_products',
        ),
    ]
