# Generated by Django 4.1.5 on 2023-02-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_rename_no_of_products_totalproductcount_number_of_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionproductdetail',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='need_vat',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='with_vat',
            field=models.BooleanField(null=True),
        ),
    ]
